---
- name: This playbook is to create a testfile1 under /home/ansadmin
  hosts: webserver [1]
  become: yes
  tasks:
  - name: creating testfile1
    file:
      path: /home/ansadmin/testfile1
      state: touch
