---
- name: Uninstall httpd package
  hosts: all
  become: true
  tasks:
  - name: stoping httpd service
    service:
      name: httpd
      state: stopped

  - name: uninstalling httpd package
    yum:
      name: httpd
      state: removed

