---
# handlers file for setup-apache-roles

- name: start apache
  service:
    name: httpd
    state: started


- name: install apache2 package
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"



